version: '4'
services:
  java-app:
    image: vvhung3/java-app:latest
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - db
    networks:
      - bridge
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: student_manage
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bridge
volumes:
  mysql-data:

networks:
  bridge: